[phases.setup]
nixPkgs = ['php83', 'php83Extensions.mongodb', 'php83Extensions.redis', 'php83Extensions.mysqli']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[start]
cmd = 'php -S 0.0.0.0:${PORT:-8000} -t .'
